version: "3.8"

services:
  redis:
    image: "redis:5"
    container_name: "redis"
    ports:
      - "6379:6379"
  aiochat_server:
    build: "."
    container_name: "aiochat_server"
    ports:
      - "8080:8080"
    links:
      - "redis"
